// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UpdatePostPermission struct {
	ID              int  `json:"id"`
	UserID          int  `json:"userId"`
	CommentsEnabled bool `json:"commentsEnabled"`
}
