version: '3.9'

services:
  go-app:
    container_name: go-app
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env.example
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    depends_on:
      pg_db:
        condition: service_healthy
    links: 
        - pg_db
    networks:
    - mynet
  pg_db:
    container_name: pg_db
    image: postgres:15.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready","--quiet"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
    - mynet

volumes:
  pgdata:
    driver: local

networks:
  mynet:
    driver: bridge